FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

# Create project directory
WORKDIR /usr/src/bot

# setup package manager
RUN apt-get update -y
RUN apt-get install -y apt-utils

# Install Deps
RUN apt-get update && apt-get install build-essential checkinstall -y
RUN apt-get install libreadline-gplv2-dev \
                    libncursesw5-dev \
                    libssl-dev \
                    libsqlite3-dev \
                    tk-dev \
                    libgdbm-dev \
                    libc6-dev \
                    libbz2-dev \ 
                    wget -y

# Install node
RUN apt-get install nodejs -y
RUN nodejs -v

# Install NPM
RUN apt-get install npm -y
RUN npm -v

# Install python
RUN wget http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz
RUN tar -xvf Python-2.7.5.tgz
RUN cd Python-2.7.5 && ./configure && make && checkinstall -y
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install matplotlib mpl_finance

# Install curl
#RUN apt-get install curl -y
#RUN curl --version

COPY strategies/TBP ./strategies/TBP
COPY package*.json ./
COPY utils ./utils

RUN npm install

RUN ls -la 

#RUN python /usr/src/bot/utils/plot.py 1585229580,247.68,248.555,246.89,247.54,1585229640,247.77,249.34,247.53,248.24,1585229700,248.33,249.76,248.33,249.32,1585229760,248.83,249.26,248.66,248.905,1585229820,248.7,248.7,247,247.015,1585229880,246.95,248.82,246.47,248.765,1585229940,248.755,249.14,247.975,248.305,1585230000,248.56,249.87,248.5,249.87
#RUN ls strategies/TBP

#CMD ["npm", "run", "startLocalWS"]
#CMD ["npm", "run", "testMinuteAggs"]
CMD ["npm", "run", "tradeTBPPaper"]