FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

# Create project directory
WORKDIR /usr/src/bot

# setup package manager
RUN apt-get update -y
RUN apt-get install -y apt-utils

# Install Deps
RUN apt-get update && apt-get install build-essential checkinstall -y
RUN apt-get install libreadline-gplv2-dev \
                    libncursesw5-dev \
                    libssl-dev \
                    libsqlite3-dev \
                    tk-dev \
                    libgdbm-dev \
                    libc6-dev \
                    libbz2-dev \ 
                    wget -y

# Install node
RUN apt-get install nodejs -y
RUN nodejs -v

# Install NPM
RUN apt-get install npm -y
RUN npm -v

# Install python
RUN wget http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz
RUN tar -xvf Python-2.7.5.tgz
RUN cd Python-2.7.5 && ./configure && make && checkinstall -y
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install matplotlib mpl_finance

# Install curl
#RUN apt-get install curl -y
#RUN curl --version

COPY strategies/TBP ./strategies/TBP
COPY package*.json ./
COPY utils ./utils

RUN npm install

RUN ls -la 

CMD ["npm", "run", "tradeTBPPaper"]