---
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  push_image:
    docker:
      - image: node:8.16.2-stretch
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Install Python
          command: apt-get update && apt-get install -y python3
      - run:
          name: Check pip
          command: pip3 --version
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name: Clean previous image
          command: npm run cleanPreviousImage
      - run:
          name: Build, Tag, and Push Image to ECR
          command: npm run buildTagPushImage

  deploy_strategy_cfn:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Install Python
          command: apt-get update && apt-get install -y python3
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name:  Deploy Service Stack
          command: npm run deployTBPService

workflows:
  version: 2
  deploy_ecs_service_stack:
    jobs:
      - push_image:
          filters:
            branches:
              only: master
      - deploy_strategy_cfn:
          requires:
            - push_image
          filters:
            branches:
              only: master
      