---
version: 2
jobs:
  push_image:
    docker:
      - image: 503921593645.dkr.ecr.us-west-2.amazonaws.com/utility:buildImage
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name: Clean previous image
          command: npm run cleanPreviousImage tbp
      - run:
          name: Start Docker
          command: service docker start
      - run:
          name: Build, Tag, and Push Image to ECR
          command: npm run buildTagPushImage

  deploy_strategy_cfn:
    docker:
      - image: 503921593645.dkr.ecr.us-west-2.amazonaws.com/utility:buildImage
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name:  Deploy Service Stack
          command: npm run deployTBPService

workflows:
  version: 2
  deploy_ecs_service_stack:
    jobs:
      - push_image:
          filters:
            branches:
              only: master
      - deploy_strategy_cfn:
          requires:
            - push_image
          filters:
            branches:
              only: master
      