---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
jobs:
  clean_prev_image:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name: Clean previous image
          command: npm run cleanPreviousImage

  deploy_strategy_cfn:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Set Debian Env Variable
          command: export DEBIAN_FRONTEND=noninteractive
      - run:
          name: Setup Package Manager for Python Install
          command: apt-get update -y && apt-get install -y apt-utils
      - run:
          name: Install Python
          command: apt-get install -y python3-pip
      - run:
          name: Install awscli
          command: pip3 install awscli
      - run:
          name: Hydrate Script Dependencies
          command: npm install
      - run:
          name:  Deploy Service Stack
          command: npm run deployTBPService

workflows:
  version: 2.1
  deploy_ecs_service_stack:
    jobs:
      - clean_prev_image:
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          requires:
            - clean_prev_image
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          path: ./strategies/TBP/Dockerfile
          region: AWS_REGION
          repo: tradingcluster
          tag: 'tbp'
          filters:
            branches:
              only: master
      - deploy_strategy_cfn:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
      